import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/footer";

// Fonts
const plusJakartaSans = Plus_Jakarta_Sans({
  weight: "400",
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const barlowCondensed = Barlow_Condensed({
  weight: "700",
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
});

// Metadata básico
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Forçar tema claro via viewport (Next.js 14+)
export const viewport = {
  colorScheme: "light",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      data-theme="light"
      className={`${plusJakartaSans.variable} ${barlowCondensed.variable}`}
    >
      <body className="antialiased bg-white text-black">
        {children}
        <Footer />
      </body>
    </html>
  );
}
