import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/footer";
import ForceLightTheme from "@/components/ui/force-light-theme";

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: "400",
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const barlowCondensed = Barlow_Condensed({
  weight: "700",
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" data-theme="light" style={{ colorScheme: "light" }}>
      <head>
        <meta name="color-scheme" content="light" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="supported-color-schemes" content="light" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Força tema claro imediatamente
              (function() {
                document.documentElement.style.colorScheme = 'light';
                document.documentElement.setAttribute('data-theme', 'light');
                document.documentElement.classList.remove('dark');
                document.documentElement.style.backgroundColor = 'white';
                document.documentElement.style.color = '#1a1a1a';
                
                // Previne flash de conteúdo escuro
                if (document.body) {
                  document.body.style.colorScheme = 'light';
                  document.body.style.backgroundColor = 'white';
                  document.body.style.color = '#1a1a1a';
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={` ${plusJakartaSans.variable} ${barlowCondensed.variable}  antialiased`}
        style={{ colorScheme: "light" }}
      >
        <ForceLightTheme />
        {children}
        <Footer />
      </body>
    </html>
  );
}
